version: '3'

services:
    postgresDB:
        image: postgres
        hostname: postgres
        ports:
            - '5432:5432'

    localstack:
        image: localstack/localstack:latest
        container_name: localstack_demo
        ports:
            - '4563-4599:4563-4599'
            - '8055:8080'
        environment:
            - SERVICES=s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - './.localstack:/tmp/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'

    api:
        build: .
        env_file:
            - .env
        environment:
            WAIT_HOSTS: postgresDB:5432
            WAIT_HOSTS: localstack:4572
        ports:
            - '8080:8080'
        depends_on: 
            - postgresDB
            - localstack
